### ISSUE TITLE
WAR package can't be deployed on GF

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibiserv#6]
The complete project can be build and package into a single WAR using MVN >= 3.0 and Java 8 , but the resulting war archive can't be deployed on a GlassFish4 application server. Seems to be an dependency problem. When comparing the WAR with a previous builded WAR (using ant/ivy) there is a different how the depended jars are located inside the package (completely unordered vs. alphabetic ordered).

**Comment by pbelmann** [comment]
solved with PR #8
